language: node_js
node_js:
  - "16"
cache: npm 
# sudo: false

install: 
  - npm ci 
script: 
  - npm test 
  - npm run build 

branches:
  only:
  - all
 
cache:
  directories:
    - node_modules
 
deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key: HEROKU_API_KEY
  app: studnt-portal