version: 2.1

orbs:
  node: circleci/node@4.7
  heroku: circleci/heroku@0.0.10

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:  
          requires:
            - build
          filters:
            branches:
              only: master
